# Generated by Django 5.2.3 on 2025-06-15 18:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_profile', models.CharField(choices=[('low', 'Düşük Risk'), ('medium', 'Orta Risk'), ('high', 'Yüksek Risk')], max_length=10, verbose_name='Risk Profili')),
                ('investment_duration', models.CharField(choices=[('short', 'Kısa Vadeli (1-2 yıl)'), ('medium', 'Orta Vadeli (3-5 yıl)'), ('long', 'Uzun Vadeli (5+ yıl)')], max_length=10, verbose_name='Yatırım Süresi')),
                ('deposit_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mevduat Yüzdesi')),
                ('gold_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Altın Yüzdesi')),
                ('stock_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Hisse Senedi Yüzdesi')),
                ('crypto_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kripto Para Yüzdesi')),
                ('expected_annual_return', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Tahmini Yıllık Getiri (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Yatırım Önerisi',
                'verbose_name_plural': 'Yatırım Önerileri',
                'unique_together': {('risk_profile', 'investment_duration')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Yaş')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aylık Gelir (TL)')),
                ('current_savings', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mevcut Birikim (TL)')),
                ('investment_duration', models.CharField(choices=[('short', 'Kısa Vadeli (1-2 yıl)'), ('medium', 'Orta Vadeli (3-5 yıl)'), ('long', 'Uzun Vadeli (5+ yıl)')], max_length=10, verbose_name='Yatırım Süresi')),
                ('risk_question_1', models.PositiveIntegerField(help_text='0: Kesinlikle evet, 1: Evet, 2: Hayır, 3: Kesinlikle hayır', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Paranızı kısa sürede harcamayı planlıyor musunuz?')),
                ('risk_question_2', models.PositiveIntegerField(help_text='0: Hiç yok, 1: Az, 2: Orta, 3: Çok yüksek', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Piyasa dalgalanmalarına ne kadar toleransınız var?')),
                ('risk_question_3', models.PositiveIntegerField(help_text='0: Çok rahatsız eder, 1: Rahatsız eder, 2: Az rahatsız eder, 3: Hiç rahatsız etmez', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Yatırımınızın aniden %10 değer kaybetmesi sizi ne kadar rahatsız eder?')),
                ('risk_question_4', models.PositiveIntegerField(help_text='0: Kesinlikle hayır, 1: Hayır, 2: Evet, 3: Kesinlikle evet', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Yüksek kazanç için beklemeyi kabul eder misiniz?')),
                ('risk_profile', models.CharField(blank=True, choices=[('low', 'Düşük Risk'), ('medium', 'Orta Risk'), ('high', 'Yüksek Risk')], max_length=10, null=True, verbose_name='Risk Profili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='UserInvestmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Yatırım Tutarı (TL)')),
                ('projected_return_1_year', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='1 Yıllık Tahmini Getiri (TL)')),
                ('projected_return_5_year', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='5 Yıllık Tahmini Getiri (TL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.investmentrecommendation', verbose_name='Yatırım Önerisi')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.userprofile', verbose_name='Kullanıcı Profili')),
            ],
            options={
                'verbose_name': 'Kullanıcı Yatırım Sonucu',
                'verbose_name_plural': 'Kullanıcı Yatırım Sonuçları',
            },
        ),
    ]
